{
  config,
  pkgs,
  lib,
  ...
}:
{
  nixpkgs.config.permittedInsecurePackages = [ "libsoup-2.74.3" ];
  environment.systemPackages = with pkgs; [
    (discord.override {
      withVencord = true;
    })
    easyeffects
    jdk21
    kdePackages.dolphin
    waybar
    hyprpaper
    kitty
    rofi
    git
    gcc
    gnumake
    pkg-config
    nodejs_22
    python3
    unzip
    ripgrep
    pavucontrol
    networkmanager
    eww
    heroic
    godot
    blender
    gh
    obsidian
    wireplumber
    libgtop
    bluez
    bluez-tools
    dart-sass
    wl-clipboard
    upower
    gvfs
    gtksourceview3
    libsoup_3
    gtk2-x11
    gtk2
    logiops
    vesktop
    r2modman
    killall
    gamescope
    p7zip
    protontricks
    kdePackages.wayland-protocols
    kdePackages.qtwayland
    kdePackages.qt6gtk2
    kdePackages.qt6ct
    kdePackages.qt5compat
    curl
    alejandra
  ];
}
